### PR TITLE
Adding virulence spell to player books (Envenomations, Alchemy)

### PR DESCRIPTION
**Pull request by nubletcrawler**
Virulence to player spell books (split from wands as requested)

-The spell (level 4, Hex/Pois) gets a slight enchantment power boost like Slow.
-Monsters with rP+ get to 0; Monsters with 0 get to rP-; Monsters with rP+++ (immune) are unaffected.
-Monsters (unlike players) can stack multiple rP+ items to cancel out the effect (see monster::res_poison, monster.cc)

The choice of books/spellpower/level is pretty arbitrary - you may want to, for example, put it into the VM starting book and nerf the enchantment boost, to make VM a consistently more viable start.

### CODE REVIEW

**Comment by Patashu** [comment]
I think this could go in VM book pretty safely - it's not like VM is that broken to begin with. (All the other foo elementalist starts have multiple amazing spells, while VM gets no spells that help when you're faced with an rPois+ boi.)

**Comment by nubletcrawler** [comment]
Maybe that's the right thing to do; balancing this is a little tricky since there is no other spell with a similar effect to use as a guideline/reference. I tried it from about D:10 onwards in the current iteration (lvl 4, slight enchantment boost) and it felt almost too easy to be in a starting book. However, on the other hand how early you find the spell is essentially RNG. I'd hear a word from Flood and/or the thread and then eventually change it.

**Comment by Patashu** [comment]
I'd say the guideline should be Confuse - if you can Confuse an enemy, it is usually as good as dead. Judging by that, and the fact that this isn't a Hexes-primary background, if this was in the VM starting book, level 4 and remove the Slow bonus to beating MR is probably correct, or otherwise making it more unwieldy than confuse.

**Comment by nubletcrawler** [comment]
Thinking about it again, moving it to the starting book makes sense, since while confuse has more in common with the rest of starting book hexes (therefore less varied array of spells to deal with enemies) it also has utility uses, such as retreating from a confused enemy when you're not confident enough, and it's easier to learn. I'll see to fixing this.

**Comment by Floodkiller** [comment]
Merged, closing PR.

**Pull request closed without merging**
