### PR TITLE
Allow walls to be disintegrated once more

### PR DESCRIPTION
**Pull request by Patashu**

### CODE REVIEW

**Comment by Floodkiller** [comment]
Can you split this into two separate pull requests?  Neither really relies on the other existing to work.

These will have to wait to merge until a pull request survey is done, by the way.

**Comment by Patashu** [comment]
"Can you split this into two separate pull requests?" Sure. Is there an easy way to move commits from one branch to another, or do I just need to do some grunt work?

**Comment by Floodkiller** [comment]
You'll want to make another branch and cherry-pick one of the commits over (and make a pull request with that branch), then revert that commit on this branch after that's done.  I can squash the revert messages out when merging, so don't worry about those.

**Comment by Patashu** [comment]
I had to type raw git commands into git bash. I AM A PROGRAMMING GOD! Let me know if I fucked it up somehow.

**Comment by Floodkiller** [comment]
Merged relevant commit, closing PR.

**Pull request closed without merging**
