### PR TITLE
Araganzar crablanguage

### PR DESCRIPTION
**Pull request by araganzar**
Add crab language to crawl.   May need some regex work to prevent words like "self" that contain "elf",etc but would like to see if this old code change even works before going further...

### CODE REVIEW

**Comment by Floodkiller** [comment]
You'll want to run git rebase to condense your commits into a single one, as they all need to be together in order to add the language.

Also, melial is currently subbed with "", which should probably be replaced before merging (do this before doing the git rebase).

I'll merge this once the above is fixed without requiring thread vote, because it doesn't actually change gameplay and is just an option in an rcfile.

**Comment by araganzar** [comment]
It won't let me rebase or squash. I generally do most of my work on local
repos so I'm really inexperienced dealing with forks on github.

I tried another request because the docs said there are options to squash
and rebase but I think only you see those:
https://github.com/blog/2243-rebase-and-merge-pull-requests

Allegedly, you can tell it to rebase my commits and it will automatically
condense them.

If that doesn't work do I clone my fork locally and rebase there?

**Comment by Floodkiller** [comment]
Just an update that I'm not ignoring this; I broke stuff with Singularity and am trying to fix it before merging this (found the options for squashing and merging).  If the other pull request you made is identical to this one, go ahead and close it because I can squash this one.

**Comment by araganzar** [comment]
Dude, I feel your pain.  I spent like 8 hours trying to figure out how to
have a unique I made up drop the gold he's carrying at a certain HP
percentage.  I gave up.

It's goddamn impossible to do anything unless you have a working example in
code.  The spawning of items and building of levels is particularly
byzantine.

I would caution you to not learn the code well as it will result in you
being too useful to other people to get anything done yourself.

I'm happy to squash, I will need a local repo eventually.  I thought if
there was an easy solution on your end it would ease your pain as well as
lower the bar for others.

The new pull request I made has the fix you asked for to melials as well as
some other regex fixes, that's it.   Don't make it a huge priority, this is
mainly me feeling out the contribution process before doing any real work.

**Review by Floodkiller — CHANGES_REQUESTED** [review]
On initfile.cc, line 3415:
's' character outside string quotes is causing the build to fail.

**Pull request merged**
