### PR TITLE
Revive Singularity

### PR DESCRIPTION
**Pull request by Patashu**
To easily test enemy Singularity, you can spawn an enemy that knows Singularity as follows:
enable wizard mode with &
&
m
ancient lich hd:20 spells:singularity.50.wizard

Change monster/hd as desired.

### CODE REVIEW

**Comment by Floodkiller** [comment]
I'll have time to test it out this weekend and merge if it doesn't break anything.

A couple formatting things before I merge: convert tabs to spaces and run checkwhite.  Tabs to spaces is needed because the rest of the repository is already formatted to spaces, so it looks off when reviewing the code outside a normal text editor (you can see an example of this on the GitHub commit summary).  Checkwhite (source/util/checkwhite) clears out any extra spaces that were left over from editing, but it's not as big a deal if this isn't done because I still need to run it again for my own changes.

**Comment by Patashu** [comment]
Done. (It also caught some whitespace errors from other gooncrawl changes, may as well fix them as well.)

I have it on my mind to revive and add many spells (as well as simple changes and other mechanics). Should I submit them in pull requests as I do them (letting you decide if they go in or not), or wait until they have been voted on in the SA topic before making a pull request for anything? I will follow your desire.

**Comment by Floodkiller** [comment]
If you submit them as pull requests, I'll have them as a separate poll from the feature requests.  It depends on whether you want to put in the work now and potentially have it rejected (but implemented faster if accepted), or only put in the work after it's been approved.

**Comment by Patashu** [comment]
Ok, cool. And I should make a separate branch on my repo for each individual change, right? And then they can each be concurrently existing pull requests that can be accepted/rejected/updated separately.

**Comment by Floodkiller** [comment]
Yep, that would probably be the best way to do it.

**Pull request merged**
