### PR TITLE
Time Stop (lv9 hexes)

### PR DESCRIPTION
**Pull request by Patashu**
Time Stop is a level 9 spell that prevents time from passing for the next 1+div_rand_round(spellpower, 50) turns. While Time Stop is in affect:
-All monsters have 0 EV and are at least weakly stabbable (confusion tier of stabs)
-Noise doesn't propagate (but it will at the end of the spell), time doesn't pass, durations don't tick down and monsters cannot react in any way to you
-Enemies cannot follow you across stairs
Time Stop will end early if you blink or teleport.
Time Stop and Serpent's Lash are mutually exclusive.
When Time Stop ends, you will be exhausted for about a dozen turns, and exhaustion prevents casting Time Stop.

An alternate way to implement Time Stop would be to make it count down auts instead of turns. This would give it synergies with haste, swiftness, speed brands and quick blades, for example. It wouldn't be hard to do (just go to check_time_stop() in main and make it remove a value from ATTR_TIME_STOP equal to time_elapsed in auts, and then make casting time stop give you 10x as much of the attribute) and could be cooler.

If Time Stop doesn't feel strong enough, it can be buffed by:
* Making it last longer.
* Making the exhaustion shorter.
* Making enemies be sleep-tier stabbable during it.
* Removing the translocation ban.
* Silencing all noise made during Time Stop, instead of propagating it afterwards.
* Making monsters unable to be disturbed (for example waking up due to damage) during it.

If Time Stop feels too strong, it can be weakened by:
* Making it shorter.
* Making the exhaustion longer.
* Making it drain you, contam you, slow you afterwards, or some other additional debuff.
* Making it, instead of totally preventing time pass, slow time to a crawl (all actions take 0.1 auts to complete). This would also let enemies react, noise propagate like normal, etc. and it'd come with a removal of the translocation ban, since it would no longer be necessary.

I'm not very confident on how Time Stop should be implemented in a way that's fun but not brokenly OP, so I'm open to feedback.

Also, I thought about Time Stop making it so projectiles (like arrows and Iron Shot) hang in the air and resume their flight when Time Stop ends, like you're DIO with the knives and all, but as cool as it sounds it doesn't really change the gameplay and it would probably be a pain to code.

EDIT: SA user 'apple' has a cool idea:

"A fun alternative to stabs could be to send targets flying based on a combination of damage and/or hits taken: picture Cerebov getting hit with a great mace 6 times during time stop, sending him flying into a brimstone fiend, probably killing the fiend while you wait at the point of impact to finish off Cerebov. I guess the idea would be to provide something close to dagger stabby effectiveness but with arbitrary weapons while being more interactive.

It might be too complicated to code the trajectory based on the direction from which they take damage (and whether you change positions between hits), but the code for force lance and Gell's gravitas could be reused, at least."

I'm going to try implementing this + a change to AUT timing to see if it spices up Time Stop enough.

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
I haven't tested this, but you may want to check how the spell interacts with multi-turn actions, such as putting on/taking off armour. Wizmode freeze time doesn't deal with such cases correctly.

**Comment by Patashu** [comment]
I did find out that delays were broken at first - fixed in commit 3 :D

**Comment by Patashu** [comment]
Time Stop MK2 is ready.

1)

Time based on AUTs instead of turns.

2) 

Momentum is stored up during Time Stop. When Time Stop ends, enemies will be sent flying back based on the direction of their last hit, and the total damage they took.

Currently the direction used is:
-if it's a beam/bolt - the direction of the beam/bolt
-if it's an explosion (like fireball) - the direction from the explosion center that monster was
-otherwise, the direction the monster is from the player

We don't have to handle every case (like monsters hitting each other), because most actions are impossible during Time Stop.

Currently enemies are sent back
 floor(log(damage)/log(2.5)) tiles. If you want to try a different formula (for example one that launches less distance at low damage), head to spl-selfench.cc stasis_launch and swap it out.

I also fixed a bug where cblink didn't end time stop.

Other things to consider: What kinds of enemy reactions should be possible during Time Stop (can they be disturbed, can they shout, etc). No special code ATM to prevent them, but maybe there should be.

**Comment by Floodkiller** [comment]
Merged, closing PR.

**Pull request closed without merging**
