### PR TITLE
Add Blade of Disaster spell

### PR DESCRIPTION
**Pull request by grasida**
My attempt at a high level, short term, tactically rich charms spell for hybrid blasters. It still should probably be considered a draft, since I've only tested it for major issues.

### CODE REVIEW

**Comment by Floodkiller** [comment]
Go through your changes and convert tabs to spaces (1 tab:4 spaces) to fit the rest of the codebase.  Otherwise the formatting can get screwy (you can kind of see how this looks by looking at the commitdif details).

**Review by Floodkiller — COMMENTED** [review]
Some whitespace left over in some spots; run checkwhite in the source/util folder to find and get rid of it.

Missing end-of-file lines for spl-selfench.cc, spl-selfench.h, spl_summoning.h: hit Enter to leave a terminating line at the end of the file.

I'll pull it into a branch to test it out once I am able to.

**Comment by grasida** [comment]
Okay, thanks! Let me know if there's anything I missed and if you find any issues.

**Comment by Floodkiller** [comment]
Messed around with various stuff and it looks stable.  Only thing to point out is the status+log describing it as "blades" if you are unarmed.  You could have the status+log text change depending on if you are armed/unarmed, or rephrase the lines to be vague enough for both.  Also, maybe mention that it only works with melee attacks (no ranged) somewhere in the description, since it works with unarmed which isn't a blade.

Anyway, it's not a dealbreaker, so I'll throw a poll up in the thread to vote on whether this gets merged.

**Comment by grasida** [comment]
Yeah, I wrote a lot of that very quickly and casually before I actually started working on the spell itself and before the design was finalized. I'll definitely change the description and probably the name. The mechanics of the spell probably need some work, too, since I want it to be possible to blow yourself up with it, but right now it's highly likely that you'll blow yourself up.

**Comment by Floodkiller** [comment]
Merged as per outcome of survey.

**Pull request merged**
