### PR TITLE
Add Fists of Thunder unrand

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
I don't mind if you change the attack flavour, but I thought it would be helpful to have a skeleton of code already in place. If you want to support using these with claws 3 it will be a lot of extra work (maybe easiest to create a new gloves variant item, like hat/helmet).

---
This change is [Reviewable](https://reviewable.io/reviews/floodkiller/crawl/9)

### CODE REVIEW

**Comment by Floodkiller** [comment]
Just letting you know I'm not ignoring this, just holding off until I can get around to compiling a poll for pull requests/mainline crawl major features to vote on for implementing.

**Comment by Floodkiller** [comment]
Fixed the commit (no playerdoll sprite for Fists of Thunder, so I just swapped it out with glove_white) and changed the item tile out for one by Metoron.  It's merged now, so closing PR.

**Comment by alexjurkiewicz** [comment]
🙌 i missed the discussion for this! Can you link the thread page?
Interested to read people's thoughts

**Comment by Floodkiller** [comment]
I think there was some rough discussion of the concept on this page, but nothing directly related to your pull request that I found (from a quick Google search):
https://forums.somethingawful.com/showthread.php?threadid=3845579&pagenumber=3

It passed with 41/46 yes votes in the survey, so a lot of people were willing to see it in at least.

**Pull request closed without merging**
